### ISSUE TITLE
How can I make the physics to be deterministic?

### ISSUE THREAD

**Issue by 89trillion-ziqiang** [felipeek/raw-physics#4]
Hi,  I want to use this physics to in a game. 

However, the game require that the physics should be deterministic, otherwise different user will see different results.  And we cannot save replay record with the indeterministic physics.

Is there any solution to make it to be deterministic?  Thank you!

**Comment by felipeek** [comment]
Hi @89trillion-ziqiang. Theoretically, the simulation algorithm is already deterministic. Are you seeing different results each run? The only thing you need to ensure is that the "delta time" (dt parameter in pbd_simulate) is the same.

If you keep the "Fix simulation for FPS ... " checkbox enabled in the example code the dt will be fixed, making the simulation deterministic. If you unmark the checkbox, then dt will vary depending on your FPS and therefore the results will not be predictable.

Let me know if you are seeing unpredictable results even when dt is fixed.

**Comment by 89trillion-ziqiang** [comment]
I don't see fix math using in this repo.  The float is indeterministic on different platform.  Thus, different result on x86 or arm.

About deterministic physics, I only find  

https://github.com/erwincoumans/tiny-differentiable-simulator  
It has the option to use the included fix-point integer math, that provide cross-platform deterministic computation.

**Comment by felipeek** [comment]
Now I see what you mean by 'deterministic'. Yeah, there is no such guarantee here. All math is done using 64-bit floating point values.

**Comment by 89trillion-ziqiang** [comment]
Thank you. I'll close this issue.
